# Generated by Django 3.2 on 2023-10-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_auto_20231013_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
